Nicer formatting of git hook output

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -2,16 +2,7 @@
 
 printf "Running pre-commit hooks\n\n"
 
-printf "Generating docs.json..."
-
-if elm make --docs=docs.json > /dev/null 2>&1; then
-    printf "Success!\n\n"
-else 
-    printf "Failed!\n\n"
-    exit 1
-fi
-
-printf "Running elm-format..."
+printf "  1. Running elm-format..."
 
 if elm-format . --yes > /dev/null 2>&1; then
     printf "Success!\n\n"
@@ -20,7 +11,16 @@ else
     exit 1
 fi
 
-printf "Staging changed files\n\n"
+printf "  2. Generating docs.json..."
+
+if elm make --docs=docs.json > /dev/null 2>&1; then
+    printf "Success!\n\n"
+else 
+    printf "Failed!\n\n"
+    exit 1
+fi
+
+printf "  3. Staging changed files\n\n"
 
 git add .
 
